#-------------------------------
# General Site Settings
title: Soy Jasmin!
logo: logo(1).png # You can add own logo.
description: About all the things I love


#-------------------------------
# Author Settings
author:
  name: Jasmine
  image: 01.jpg
  say-hello: Hello, I’m <strong>Seolhee</strong>
  bio: Write about my research interests. And share my <a href="#">Exploration of Happiness in Mindful Life</a>.


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: jasmine # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Facebook Feed
facebook-profile: seolhee.jasmine.jeon

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: jasmine.jsh # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-DPR88N04RY # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
